### PR TITLE
Fixes #15, #17, #18, and does other improvements

### LINKED ISSUE #15: Search crashes when tokenize = true and the query ends with a space
Title says it all :) Here's an example test code:
```dart
import 'package:test/test.dart';
import 'package:fuzzy/fuzzy.dart';

void main() {
  test('Search works when tokenize = true and query ends with space', () {
    final fuse = Fuzzy(['apple juice'], options: FuzzyOptions(tokenize: true));
    expect(() => fuse.search('apple'), returnsNormally);
    expect(() => fuse.search('apple j'), returnsNormally);
    expect(() => fuse.search('apple '), returnsNormally);
  });
}
```
The first two expects succeed, but the last one fails with:
```
Expected: return normally
  Actual: <Closure: () => List<Result<dynamic>>>
   Which: threw ArgumentError:<Invalid argument(s): -1>
```

Here's the full stack trace from the test (i.e., removing the expectation):
```
dart:core                                    int.<<
package:fuzzy/bitap/bitap_search.dart 62:18  bitapSearch
package:fuzzy/bitap/bitap.dart 63:12         Bitap.search
package:fuzzy/fuzzy.dart 175:51              Fuzzy._analyze
package:fuzzy/fuzzy.dart 93:9                Fuzzy._search
package:fuzzy/fuzzy.dart 50:9                Fuzzy.search
test\test.dart 9:10                          main.<fn>

Invalid argument(s): -1
```

### PR DESCRIPTION
**Pull request by luistrivelatto**
Added tests reproducing the crash in #15, and fixed by removing empty tokens after tokenizing.

### CODE REVIEW

**Comment by luistrivelatto** [comment]
Added some commits that also fixes #17, #18, and fixes an apparent bug in weighted search.

**Comment by ghost** [comment]
Thanks @luistrivelatto. I'll use your fork and report back.

**Comment by comigor** [comment]
Hello @luistrivelatto, thank you so much for this PR (and sorry for the late reply)!
I'll fix the pipeline and review it soon!

**Comment by luistrivelatto** [comment]
Thanks @comigor. Sorry about piling up commits in a single PR, I've changed the title to reflect the changes better.

I'm currently using the lib for tokenized, weighted search, and the results are satisfying. I've gathered 50+ search tests on my data, and only one of them didn't give the expected intuitive results, but I don't consider it a fault of the algorithm because it's due to some use case-specific "gotcha" (a search token ends up being substring of two item tokens, then gives 2 perfect matches when I expected one). I can live with that hehe

Thanks for the package :)

**Comment by comigor** [comment]
@luistrivelatto No problems! Thanks for stepping up and fix those issues!

Before we merge, could you please update the CHANGELOG with all the changes you did?

**Comment by luistrivelatto** [comment]
Sure, done.

**Comment by comigor** [comment]
Thank you very much!

**Comment by comigor** [comment]
Published as [0.3.0](https://pub.dev/packages/fuzzy/versions/0.3.0)

**Pull request merged**
