### PR TITLE
Migrate to null safety

### PR DESCRIPTION
**Pull request by anirudhb**
Migrates the fuzzy library to null safety. There are now no dependencies. `package:meta` is obsolete due to the introduction of the `required` keyword, and `package:latinize` seemed to have a dead repo so I just put its code here (so that it is null safe.)

I would really like if this null safety prerelease could be published quickly on pub.dev, I'd like to use it for one of my projects. Thanks for making this great library as always!

### CODE REVIEW

**Comment by anirudhb** [comment]
n.b. tests are failing since the container uses flutter stable, which only has dart 2.10 (NNBD is enabled in 2.12-dev, which is only available on dev/master IIRC)

**Comment by comigor** [comment]
Hello @anirudhb, thank you so much for this PR (and sorry for the late reply)!
I'll fix the pipeline and take a look at this soon

**Comment by comigor** [comment]
I've updated `latinize` and migrated it to nullsafety, and merged this PR with master.
We just need to wait for [latinize pipeline](https://github.com/lucasmafra/latinize/runs/1669273480) to be fixed and it should be good to go!

**Comment by comigor** [comment]
@anirudhb Thanks for the help, it was released as [0.4.0-nullsafety.0](https://pub.dev/packages/fuzzy/versions/0.4.0-nullsafety.0)

**Pull request merged**
